name 'mvantellingen-nginx'
version '2.3.0'

author 'Alessandro Franceschi - Maintainer Javier Bertoli'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/mvantellingen/puppet-nginx'
summary 'Puppet module for nginx'
description 'This module installs and manages nginx. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'puppetlabs/concat', '>=1.0.0'
